{
 "title": "AI4X Hackathon Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Average Service Level Latency ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component) (\r\n  abs(ai4x_hack_component_latency_seconds_sum{component=~\"NMT|LLM|BackNMT|TTS\"})\r\n)\r\n/\r\nsum by (component) (\r\n  ai4x_hack_component_latency_seconds_count{component=~\"NMT|LLM|BackNMT|TTS\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Pipeline Response time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ai4x_hack_request_duration_seconds_sum{service=\"pipeline\"})\r\n/\r\nsum(ai4x_hack_request_duration_seconds_count{service=\"pipeline\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Characters Processed (NMT & TTS)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (data_type) (ai4x_hack_data_processed_total{data_type=~\"nmt_characters|tts_characters\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # Customers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (customer) (ai4x_hack_data_processed_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens Processed (LLM)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ai4x_hack_data_processed_total{data_type=\"llm_tokens\"})",
     "legendFormat": "{{data_type}}"
    }
   ]
  }
 ]
}