{
 "title": "Customer 1 Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service Level Quota Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_hack_customer_quota_limit{customer=\"customer1\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Service Level Quota Remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_hack_customer_quota_remaining{customer=\"customer1\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Service Quota Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_hack_customer_quota_usage_percent",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}