{
 "title": "Integrated Dashv2 - Ultimate QOS Overview",
 "time": { "from": "2025-09-03T00:16:22.185Z", "to": "2025-09-05T06:54:20.611Z" },
 "panels": [
  {
   "title": "Application level Throughput (Req/Second)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (app) (ai4x_throughput_requests_per_second)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(sum(ai4x_requests_total{status!=\"success\"}) or vector(0))\r\n/\r\n(sum(ai4x_requests_total) or vector(1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Customer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ai4x_requests_total", "legendFormat": "{{customer}}" }
   ]
  }
 ]
}