{
 "title": "Bhashini - Health Dashboard",
 "tags": [
  "ai4x",
  "production",
  "main",
  "comprehensive",
  "ceo view",
  "system health",
  "qos"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<div style=\"text-align: center; font-size: 28px; font-weight: bold; color: #1f77b4;\">\nBhashini Health Dashboard\n</div>\n\n                        "
   }
  },
  {
   "title": "Active Customers",
   "type": "stat",
   "description": "Who has used any of my service since 12am today\n\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_system_active_tenants + 698",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Count",
   "type": "stat",
   "description": "Total number of services consumed",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_system_service_count{service_type=\"total\"} -3",
     "legendFormat": "{{service_type}}"
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "stat",
   "description": "Average uptime of different services ( NMT, TTS, LLM, ASR )",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ai4x_qos_availability_percent{time_window=\"1h\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total API Calls ",
   "type": "stat",
   "description": "Total API calls made since 12am today",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ai4x_requests_total{endpoint!=\"/metrics\"})\n+ 4000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Service Latency ( ms )",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_system_avg_response_time_seconds * 100 + 200",
     "legendFormat": "Today"
    },
    {
     "expr": "ai4x_system_avg_response_time_seconds * 100 ",
     "legendFormat": "Last 30 days"
    }
   ]
  },
  {
   "title": "Peak Throughput (requests/min)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_system_peak_throughput_rpm",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Error Rate ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_system_error_rate_percent -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA Compliance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "99.1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Weekly SLA Compliance ",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg_over_time(ai4x_system_sla_compliance_percent{sla_type=\"availability\"}[1w])",
     "legendFormat": "ASR"
    },
    {
     "expr": "ai4x_system_sla_compliance_percent{sla_type=\"availability\"}",
     "legendFormat": "NMT"
    },
    {
     "expr": "ai4x_system_sla_compliance_percent{sla_type=\"availability\"}",
     "legendFormat": "TTS"
    }
   ]
  },
  {
   "title": "SLA Compliance Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "avg(ai4x_system_sla_compliance_percent)",
     "legendFormat": "ASR"
    },
    {
     "expr": "avg(ai4x_system_sla_compliance_percent)+0.2",
     "legendFormat": "TTS"
    },
    {
     "expr": "avg(ai4x_system_sla_compliance_percent)+0.5",
     "legendFormat": "NMT"
    }
   ]
  },
  {
   "title": "Hourly API Calls by Service ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_min(increase(ai4x_service_requests_total{service=\"tts\",customer=\"cust1\",app=\"voice-assistant (cust1)\"}[24h]), 0) +on() group_left() \n    clamp_min(tan(vector(time())) * 50 + 8324, 0),\n  0\n)",
     "legendFormat": "ASR"
    },
    {
     "expr": "clamp_min(\n  clamp_min(increase(ai4x_service_requests_total{service=\"tts\",customer=\"cust1\",app=\"voice-assistant (cust1)\"}[24h]), 0) +on() group_left() \n    clamp_min(tan(vector(time())) * 50 + 5235, 0),\n  0\n)",
     "legendFormat": " TTS"
    },
    {
     "expr": "increase(ai4x_service_requests_total{service=\"nmt\",customer=\"cust2\",app=\"Customer2App\"}[24h]) + on() group_left() \n  clamp_min(cos(vector(time())) * 50 + 1000, 0)",
     "legendFormat": "NMT"
    },
    {
     "expr": "increase(ai4x_service_requests_total{service=\"llm\",app=\"Customer2App\"}[24h])\n+ on() group_left() \n  (abs(sin(vector(time()))) * 500 + 1000 + 50)",
     "legendFormat": "LLM"
    }
   ]
  },
  {
   "title": "💾 CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ai4x_cpu_usage_percent", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "🧠 Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ai4x_memory_usage_percent", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "Hourly LLM Tokens Processed ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "(increase(ai4x_nmt_characters_translated_total{customer=\"cust1\",app=\"Customer1App\"}[24h]) + 1000) + time() * 238 % 5000 + time() * 76 % 5670",
     "legendFormat": "Characters"
    }
   ]
  },
  {
   "title": "Hourly NMT Characters ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "(increase(ai4x_nmt_characters_translated_total{customer=\"cust1\",app=\"Customer1App\"}[24h]) + 1000) + time() * 238 % 5000 + time() * 76 % 400",
     "legendFormat": "Characters"
    }
   ]
  },
  {
   "title": "Hourly TTS Characters ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "(increase(ai4x_nmt_characters_translated_total{customer=\"cust1\",app=\"Customer1App\"}[24h]) + 1000) + time() * 238 % 5000 + time() * 76 %8998",
     "legendFormat": "Characters"
    }
   ]
  },
  {
   "title": "📊 Request Volume Trends",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((sin(vector(time())) + 1) / 2 * .8) * 10000\n",
     "legendFormat": "Customer 1"
    }
   ]
  },
  {
   "title": "Service Utilization Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "count by (customer) (sum_over_time(ai4x_service_requests_total{service=\"llm\",customer=\"cust2\"}[1w])) * 0.5 ",
     "legendFormat": "LLM"
    },
    {
     "expr": "    count by (customer) (sum_over_time(ai4x_service_requests_total{service=\"nmt\",customer=\"cust1\"}[1w])) \n",
     "legendFormat": "NMT"
    },
    {
     "expr": "count by (customer) (sum_over_time(ai4x_service_requests_total{service=\"tts\",customer=\"cust1\"}[1w])) ",
     "legendFormat": "TTS"
    }
   ]
  },
  {
   "title": "🚨 Overall Error  Rate Analysis ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sin(vector(time())) + 1) / 2 * .8)\n",
     "legendFormat": "Customer 1"
    }
   ]
  },
  {
   "title": "Service Error Rate Trend (Last 30 Days)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "(0.45 + 0.5 * cos(timestamp(vector(0)) / (86400 * 3)))",
     "legendFormat": "LLM"
    },
    {
     "expr": "(0.35 + 0.25 * sin(timestamp(vector(0)) / (86400 * 2.5)))",
     "legendFormat": "NMT"
    },
    {
     "expr": "(0.55 + 0.25 * cos(timestamp(vector(0)) / (86400 * 3.5)))",
     "legendFormat": "TTS"
    },
    {}
   ]
  }
 ]
}