{
 "title": "Customer view - cust1",
 "tags": [
  "tenant",
  "qos",
  "sla"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System uptime",
   "type": "stat",
   "description": "Average uptime of different services ( NMT, TTS, LLM, ASR )",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ai4x_qos_availability_percent{time_window=\"1h\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Latency ( ms )",
   "type": "stat",
   "description": "Response time for completed reequests end to end",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_system_avg_response_time_seconds * 100  # in milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ai4x_system_error_rate_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Throughput (req/s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ai4x_requests_total{customer=\"cust1\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA Compliance ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ai4x_system_sla_compliance_percent{customer=\"cust1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA compliance by service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_qos_performance_score{customer=\"cust1\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Service Availability Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "ai4x_qos_availability_percent", "legendFormat": "{{time_window}}" }
   ]
  },
  {
   "title": "SLA Violation Alerts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_system_sla_compliance_percent{sla_type=~\"availability|response_time|error_rate\"}",
     "legendFormat": "{{sla_type}}"
    }
   ]
  },
  {
   "title": "Throughput Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "requests_per_minute" } },
   "targets": [
    {
     "expr": "sum by(customer) (rate(ai4x_requests_total{customer=\"cust1\"}[1m])) * 60",
     "legendFormat": "cust1"
    }
   ]
  },
  {
   "title": "Response Time by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (component) (ai4x_component_latency_seconds_sum)\r\n/\r\nsum by (component) (ai4x_component_latency_seconds_count)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Error Rate Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ai4x_errors_total", "legendFormat": "{{job}}" }
   ]
  }
 ]
}